export const MOTIVATIONAL_QUOTES = [
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
  { text: "Consistency is better than perfection.", author: "James Clear" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "It’s not that I’m so smart, it’s just that I stay with problems longer.", author: "Albert Einstein" },
  { text: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Your talent determines what you can do. Your motivation determines how much you are willing to do.", author: "Lou Holtz" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Productivity is being able to do things that you were never able to do before.", author: "Franz Kafka" },
  { text: "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Self-discipline is when your conscience tells you to do something and you don't talk back.", author: "W.K. Hope" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Work like there is someone working 24 hours a day to take it all away from you.", author: "Mark Cuban" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Someday is not a day of the week.", author: "Denise Brennan-Nelson" },
  { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Opportunities are usually disguised as hard work, so most people don’t recognize them.", author: "Ann Landers" },
  { text: "Don’t stay in bed, unless you can make money in bed.", author: "George Burns" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { text: "If you don't pay the price for success, you'll pay the price for failure.", author: "Zig Ziglar" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Focusing is about saying no.", author: "Steve Jobs" },
  { text: "The tragedy of life doesn't lie in not reaching your goal. The tragedy lies in having no goal to reach.", author: "Benjamin Mays" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Small progress is still progress.", author: "Anonymous" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Anonymous" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John Maxwell" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" }
]
